# Evaluate — is it real?

Runs the strategy named in `evaluate_config.py`, and every arm of its `COMPARE`, over each quarter
of `TRAIN` and `FORWARD` — about a minute for 19 quarters. Choose between arms on **train**; the
verdict is **forward**, which the choice never saw.

This is the check to run before believing the lab. Notebook 21's strategy made +4R on its 20 days
and loses 0.16R a trade over four and a half years.

In [1]:
import sys, os, warnings; warnings.filterwarnings('ignore')
for _p in (os.path.abspath('..'), os.getcwd()):
    if os.path.isfile(os.path.join(_p, 'quant', '__init__.py')) and _p not in sys.path:
        sys.path.insert(0, _p)

from quant.research.workspace import evaluate_config
from experiments.evaluate import evaluate

cfg = evaluate_config()
print(f"strategy  {cfg.STRATEGY}   {cfg.SYMBOL} {cfg.TF}")
print(f"train {cfg.TRAIN[0]}..{cfg.TRAIN[1]}   forward {cfg.FORWARD[0]}..{cfg.FORWARD[1]}")
print(f"arms      {', '.join(cfg.COMPARE) or '(none)'}")

strategy  tl_break_confirm   BTCUSDT 5m
train 2022Q1..2024Q2   forward 2024Q3..2026Q3
arms      neither, move target, fvg exit, both, no confirmation

## 1 · Run it

In [2]:
ev = evaluate(cfg)

[15:56:58] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:56:59] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:56:59] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:56:59] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:56:59] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:56:59] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:02] INFO | quant.engine | backtest done | bars=34,849 trades=33 final_cash=8906.28 return=-10.94% dd=16.24% | 46.3 ms
[15:57:02] INFO | quant.engine | backtest done | bars=34,849 trades=31 final_cash=10060.93 return=0.61% dd=7.48% | 2.5 ms
[15:57:02] INFO | quant.engine | backtest done | bars=34,849 trades=33 final_cash=9253.98 return=-7.46% dd=13.80% | 3.1 ms
[15:57:02] INFO | quant.engine | backtest done | bars=34,849 trades=31 final_cash=11172.17 return=11.72% dd=5.32% | 2.6 ms
[15:57:02] INFO | quant.engine | backtest done | bars=34,849 trades=35 final_cash=9203.82 return=-7.96% dd=12.95% | 3.7 ms
[15:57:02] INFO | quant.engine | backtest done | bars=34,849 trades=31 final_cash=10154.25 return=1.54% dd=6.22% | 2.8 ms
[15:57:02] INFO | quant.engine | backtest done | bars=34,849 trades=35 final_cash=9094.38 return=-9.06% dd=14.47% | 3.8 ms
[15:57:02] INFO | quant.engine | backtest done | bars=34,849 trades=31 final_cash=10230.24 return=2.30% dd=5.86% | 2.0 ms
[15:57:03] INFO | quant.engine | backtest done | bars=34,849 trades=35 final_cash=9042.75 return=-9.57% dd=14.47% | 3.6 ms
[15:57:03] INFO | quant.engine | backtest done | bars=34,849 trades=31 final_cash=10007.42 return=0.07% dd=6.22% | 2.3 ms
[15:57:03] INFO | quant.engine | backtest done | bars=34,849 trades=33 final_cash=8917.79 return=-10.82% dd=17.29% | 3.1 ms
[15:57:03] INFO | quant.engine | backtest done | bars=34,849 trades=30 final_cash=10453.09 return=4.53% dd=7.45% | 2.8 ms

2022Q1: 64 trades  -9.4R  (9s)

[15:57:03] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:03] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:03] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:03] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:03] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:03] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:05] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=8430.77 return=-15.69% dd=18.18% | 2.8 ms
[15:57:05] INFO | quant.engine | backtest done | bars=35,137 trades=43 final_cash=9668.04 return=-3.32% dd=10.42% | 4.5 ms
[15:57:05] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=8818.97 return=-11.81% dd=15.84% | 2.9 ms
[15:57:05] INFO | quant.engine | backtest done | bars=35,137 trades=43 final_cash=10207.08 return=2.07% dd=8.37% | 4.1 ms
[15:57:05] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=8350.74 return=-16.49% dd=19.08% | 3.3 ms
[15:57:05] INFO | quant.engine | backtest done | bars=35,137 trades=43 final_cash=9714.40 return=-2.86% dd=11.05% | 4.6 ms
[15:57:05] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=8244.54 return=-17.55% dd=19.69% | 2.9 ms
[15:57:06] INFO | quant.engine | backtest done | bars=35,137 trades=43 final_cash=9606.64 return=-3.93% dd=10.73% | 3.5 ms
[15:57:06] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=8243.99 return=-17.56% dd=20.57% | 3.5 ms
[15:57:06] INFO | quant.engine | backtest done | bars=35,137 trades=43 final_cash=9652.70 return=-3.47% dd=11.34% | 5.1 ms
[15:57:06] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=8779.54 return=-12.20% dd=13.92% | 4.3 ms
[15:57:06] INFO | quant.engine | backtest done | bars=35,137 trades=47 final_cash=10946.31 return=9.46% dd=5.90% | 3.9 ms

2022Q2: 80 trades  -20.1R  (12s)

[15:57:06] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:06] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:06] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:06] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:06] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:06] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:09] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=8971.51 return=-10.28% dd=12.64% | 11.6 ms
[15:57:09] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=8861.24 return=-11.39% dd=13.06% | 7.4 ms
[15:57:09] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=9386.32 return=-6.14% dd=10.57% | 12.9 ms
[15:57:09] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=9153.23 return=-8.47% dd=11.02% | 7.9 ms
[15:57:09] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=9180.50 return=-8.20% dd=9.55% | 6.9 ms
[15:57:09] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=8920.36 return=-10.80% dd=13.82% | 16.0 ms
[15:57:10] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=8912.80 return=-10.87% dd=12.17% | 7.8 ms
[15:57:10] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=9048.94 return=-9.51% dd=13.74% | 6.9 ms
[15:57:10] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=9010.51 return=-9.89% dd=11.21% | 4.7 ms
[15:57:10] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=8943.31 return=-10.57% dd=14.75% | 4.8 ms
[15:57:11] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=8855.16 return=-11.45% dd=13.55% | 5.8 ms
[15:57:11] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=8640.32 return=-13.60% dd=15.23% | 3.8 ms

2022Q3: 64 trades  -24.2R  (17s)

[15:57:11] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:11] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:11] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:11] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:11] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:11] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:12] INFO | quant.engine | backtest done | bars=35,137 trades=26 final_cash=9591.63 return=-4.08% dd=8.03% | 3.1 ms
[15:57:12] INFO | quant.engine | backtest done | bars=35,137 trades=11 final_cash=10676.54 return=6.77% dd=2.68% | 6.2 ms
[15:57:12] INFO | quant.engine | backtest done | bars=35,137 trades=26 final_cash=9963.49 return=-0.37% dd=6.92% | 3.2 ms
[15:57:12] INFO | quant.engine | backtest done | bars=35,137 trades=11 final_cash=10835.88 return=8.36% dd=2.09% | 4.7 ms
[15:57:13] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=9821.57 return=-1.78% dd=7.40% | 4.4 ms
[15:57:13] INFO | quant.engine | backtest done | bars=35,137 trades=12 final_cash=10316.08 return=3.16% dd=3.11% | 6.8 ms
[15:57:13] INFO | quant.engine | backtest done | bars=35,137 trades=26 final_cash=9517.57 return=-4.82% dd=8.34% | 3.2 ms
[15:57:13] INFO | quant.engine | backtest done | bars=35,137 trades=13 final_cash=10213.23 return=2.13% dd=2.92% | 4.7 ms
[15:57:13] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=9745.73 return=-2.54% dd=7.40% | 4.5 ms
[15:57:13] INFO | quant.engine | backtest done | bars=35,137 trades=13 final_cash=10093.96 return=0.94% dd=3.40% | 11.3 ms
[15:57:13] INFO | quant.engine | backtest done | bars=35,137 trades=22 final_cash=9866.53 return=-1.33% dd=6.66% | 3.9 ms
[15:57:13] INFO | quant.engine | backtest done | bars=35,137 trades=12 final_cash=10525.45 return=5.25% dd=3.89% | 4.7 ms

2022Q4: 37 trades  -4.1R  (19s)

[15:57:13] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:13] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:13] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:14] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:14] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:14] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:15] INFO | quant.engine | backtest done | bars=34,833 trades=31 final_cash=10808.94 return=8.09% dd=11.15% | 2.7 ms
[15:57:15] INFO | quant.engine | backtest done | bars=34,833 trades=23 final_cash=9181.84 return=-8.18% dd=12.54% | 3.2 ms
[15:57:15] INFO | quant.engine | backtest done | bars=34,833 trades=31 final_cash=11293.54 return=12.94% dd=9.06% | 2.8 ms
[15:57:15] INFO | quant.engine | backtest done | bars=34,833 trades=23 final_cash=9441.70 return=-5.58% dd=10.95% | 3.2 ms
[15:57:15] INFO | quant.engine | backtest done | bars=34,833 trades=31 final_cash=10937.49 return=9.37% dd=7.68% | 3.5 ms
[15:57:15] INFO | quant.engine | backtest done | bars=34,833 trades=23 final_cash=9348.22 return=-6.52% dd=11.22% | 4.3 ms
[15:57:15] INFO | quant.engine | backtest done | bars=34,833 trades=34 final_cash=11420.46 return=14.20% dd=7.28% | 2.5 ms
[15:57:16] INFO | quant.engine | backtest done | bars=34,833 trades=24 final_cash=9365.90 return=-6.34% dd=11.49% | 3.2 ms
[15:57:16] INFO | quant.engine | backtest done | bars=34,833 trades=34 final_cash=11207.14 return=12.07% dd=7.56% | 3.1 ms
[15:57:16] INFO | quant.engine | backtest done | bars=34,833 trades=24 final_cash=9365.90 return=-6.34% dd=11.49% | 4.9 ms
[15:57:16] INFO | quant.engine | backtest done | bars=34,833 trades=35 final_cash=11707.99 return=17.08% dd=8.00% | 2.7 ms
[15:57:16] INFO | quant.engine | backtest done | bars=34,833 trades=29 final_cash=9118.39 return=-8.82% dd=11.69% | 2.8 ms

2023Q1: 54 trades  -2.1R  (22s)

[15:57:16] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:16] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:16] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:16] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:16] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:16] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:18] INFO | quant.engine | backtest done | bars=35,121 trades=33 final_cash=8404.99 return=-15.95% dd=16.44% | 2.7 ms
[15:57:18] INFO | quant.engine | backtest done | bars=35,121 trades=31 final_cash=10582.45 return=5.82% dd=6.03% | 2.9 ms
[15:57:18] INFO | quant.engine | backtest done | bars=35,121 trades=33 final_cash=8843.31 return=-11.57% dd=13.29% | 2.4 ms
[15:57:18] INFO | quant.engine | backtest done | bars=35,121 trades=31 final_cash=11070.08 return=10.70% dd=5.32% | 2.6 ms
[15:57:18] INFO | quant.engine | backtest done | bars=35,121 trades=33 final_cash=8760.41 return=-12.40% dd=12.46% | 3.6 ms
[15:57:18] INFO | quant.engine | backtest done | bars=35,121 trades=33 final_cash=10457.28 return=4.57% dd=5.95% | 3.3 ms
[15:57:18] INFO | quant.engine | backtest done | bars=35,121 trades=33 final_cash=8629.38 return=-13.71% dd=14.20% | 2.5 ms
[15:57:18] INFO | quant.engine | backtest done | bars=35,121 trades=31 final_cash=10226.63 return=2.27% dd=6.28% | 2.6 ms
[15:57:19] INFO | quant.engine | backtest done | bars=35,121 trades=33 final_cash=8739.24 return=-12.61% dd=12.67% | 3.3 ms
[15:57:19] INFO | quant.engine | backtest done | bars=35,121 trades=33 final_cash=10116.77 return=1.17% dd=6.19% | 3.3 ms
[15:57:19] INFO | quant.engine | backtest done | bars=35,121 trades=38 final_cash=9192.58 return=-8.07% dd=9.46% | 2.3 ms
[15:57:19] INFO | quant.engine | backtest done | bars=35,121 trades=36 final_cash=10629.95 return=6.30% dd=5.77% | 2.5 ms

2023Q2: 64 trades  -15.8R  (25s)

[15:57:19] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:19] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:19] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:19] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:19] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:19] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:21] INFO | quant.engine | backtest done | bars=35,137 trades=41 final_cash=8852.59 return=-11.47% dd=14.24% | 2.0 ms
[15:57:21] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=9418.69 return=-5.81% dd=8.24% | 3.9 ms
[15:57:21] INFO | quant.engine | backtest done | bars=35,137 trades=41 final_cash=9668.70 return=-3.31% dd=7.45% | 2.1 ms
[15:57:21] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=9851.45 return=-1.49% dd=5.83% | 3.9 ms
[15:57:21] INFO | quant.engine | backtest done | bars=35,137 trades=41 final_cash=8964.07 return=-10.36% dd=13.16% | 2.8 ms
[15:57:21] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=9292.55 return=-7.07% dd=9.47% | 5.8 ms
[15:57:21] INFO | quant.engine | backtest done | bars=35,137 trades=42 final_cash=8787.02 return=-12.13% dd=14.06% | 2.1 ms
[15:57:21] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=9254.48 return=-7.46% dd=8.97% | 3.9 ms
[15:57:22] INFO | quant.engine | backtest done | bars=35,137 trades=42 final_cash=8897.68 return=-11.02% dd=12.98% | 2.9 ms
[15:57:22] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=9167.49 return=-8.33% dd=9.82% | 5.7 ms
[15:57:22] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=8943.96 return=-10.56% dd=13.00% | 3.0 ms
[15:57:22] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=9193.13 return=-8.07% dd=10.94% | 4.5 ms

2023Q3: 69 trades  -38.8R  (28s)

[15:57:22] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:22] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:22] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:22] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:22] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:22] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:24] INFO | quant.engine | backtest done | bars=35,137 trades=46 final_cash=10233.18 return=2.33% dd=8.43% | 3.4 ms
[15:57:24] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=8303.34 return=-16.97% dd=19.58% | 2.7 ms
[15:57:24] INFO | quant.engine | backtest done | bars=35,137 trades=46 final_cash=10977.20 return=9.77% dd=7.01% | 3.5 ms
[15:57:24] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=8693.80 return=-13.06% dd=16.32% | 4.8 ms
[15:57:24] INFO | quant.engine | backtest done | bars=35,137 trades=48 final_cash=9923.08 return=-0.77% dd=11.05% | 4.5 ms
[15:57:24] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=8506.78 return=-14.93% dd=17.61% | 3.3 ms
[15:57:24] INFO | quant.engine | backtest done | bars=35,137 trades=46 final_cash=10319.27 return=3.19% dd=8.79% | 3.2 ms
[15:57:24] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=8277.45 return=-17.23% dd=19.83% | 2.4 ms
[15:57:25] INFO | quant.engine | backtest done | bars=35,137 trades=48 final_cash=10006.56 return=0.07% dd=11.79% | 4.1 ms
[15:57:25] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=8480.25 return=-15.20% dd=17.87% | 2.9 ms
[15:57:25] INFO | quant.engine | backtest done | bars=35,137 trades=44 final_cash=11237.23 return=12.37% dd=7.39% | 3.4 ms
[15:57:25] INFO | quant.engine | backtest done | bars=35,137 trades=32 final_cash=8367.89 return=-16.32% dd=19.11% | 1.9 ms

2023Q4: 76 trades  -18.0R  (31s)

[15:57:25] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:25] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:25] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:25] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:25] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:25] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:27] INFO | quant.engine | backtest done | bars=35,137 trades=32 final_cash=10306.93 return=3.07% dd=8.14% | 3.5 ms
[15:57:27] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=8732.20 return=-12.68% dd=18.56% | 2.3 ms
[15:57:27] INFO | quant.engine | backtest done | bars=35,137 trades=32 final_cash=10767.38 return=7.67% dd=6.63% | 3.5 ms
[15:57:27] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=9074.65 return=-9.25% dd=15.91% | 2.4 ms
[15:57:27] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=10284.33 return=2.84% dd=8.14% | 4.6 ms
[15:57:27] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=8623.10 return=-13.77% dd=18.62% | 3.3 ms
[15:57:27] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=9951.57 return=-0.48% dd=8.14% | 3.3 ms
[15:57:27] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=8784.50 return=-12.16% dd=17.91% | 2.4 ms
[15:57:27] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=10196.59 return=1.97% dd=8.14% | 4.6 ms
[15:57:27] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=8674.75 return=-13.25% dd=17.98% | 3.3 ms
[15:57:28] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=10242.13 return=2.42% dd=8.76% | 3.5 ms
[15:57:28] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=8923.18 return=-10.77% dd=16.90% | 2.7 ms

2024Q1: 61 trades  -13.2R  (34s)

[15:57:28] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:28] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:28] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:28] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:28] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:28] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:30] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=10277.44 return=2.77% dd=7.32% | 4.2 ms
[15:57:30] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=9923.06 return=-0.77% dd=9.19% | 5.5 ms
[15:57:30] INFO | quant.engine | backtest done | bars=35,137 trades=34 final_cash=10717.02 return=7.17% dd=6.03% | 3.6 ms
[15:57:30] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=10401.71 return=4.02% dd=7.83% | 3.8 ms
[15:57:30] INFO | quant.engine | backtest done | bars=35,137 trades=35 final_cash=10297.58 return=2.98% dd=8.63% | 4.8 ms
[15:57:30] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=9949.89 return=-0.50% dd=7.26% | 4.6 ms
[15:57:30] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=10062.97 return=0.63% dd=7.59% | 3.2 ms
[15:57:30] INFO | quant.engine | backtest done | bars=35,137 trades=34 final_cash=9888.05 return=-1.12% dd=7.15% | 3.0 ms
[15:57:31] INFO | quant.engine | backtest done | bars=35,137 trades=35 final_cash=9921.55 return=-0.78% dd=8.90% | 4.2 ms
[15:57:31] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=9831.32 return=-1.69% dd=7.29% | 3.8 ms
[15:57:31] INFO | quant.engine | backtest done | bars=35,137 trades=34 final_cash=10008.15 return=0.08% dd=7.70% | 2.9 ms
[15:57:31] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=10052.95 return=0.53% dd=7.28% | 2.9 ms

2024Q2: 66 trades  -3.5R  (37s)

[15:57:31] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:31] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:31] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:31] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:31] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:31] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:33] INFO | quant.engine | backtest done | bars=35,137 trades=34 final_cash=10471.37 return=4.71% dd=6.27% | 3.3 ms
[15:57:33] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=10275.30 return=2.75% dd=7.78% | 2.5 ms
[15:57:33] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=10731.96 return=7.32% dd=5.16% | 3.1 ms
[15:57:33] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=10796.55 return=7.97% dd=6.04% | 2.3 ms
[15:57:33] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=9988.54 return=-0.11% dd=7.16% | 4.3 ms
[15:57:33] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=10102.50 return=1.02% dd=8.71% | 3.2 ms
[15:57:33] INFO | quant.engine | backtest done | bars=35,137 trades=35 final_cash=9945.08 return=-0.55% dd=6.97% | 3.3 ms
[15:57:33] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=9715.36 return=-2.85% dd=9.09% | 2.3 ms
[15:57:33] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=9699.06 return=-3.01% dd=7.14% | 4.2 ms
[15:57:34] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=9649.27 return=-3.51% dd=9.09% | 3.1 ms
[15:57:34] INFO | quant.engine | backtest done | bars=35,137 trades=35 final_cash=10356.60 return=3.57% dd=6.23% | 3.3 ms
[15:57:34] INFO | quant.engine | backtest done | bars=35,137 trades=39 final_cash=9888.78 return=-1.11% dd=10.03% | 2.5 ms

2024Q3: 70 trades  +5.4R  (40s)

[15:57:34] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:34] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:34] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:34] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:34] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:34] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:35] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=10682.62 return=6.83% dd=11.91% | 2.2 ms
[15:57:35] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=9269.61 return=-7.30% dd=11.82% | 2.4 ms
[15:57:36] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=11267.72 return=12.68% dd=10.34% | 2.1 ms
[15:57:36] INFO | quant.engine | backtest done | bars=35,137 trades=38 final_cash=9745.86 return=-2.54% dd=9.06% | 2.3 ms
[15:57:36] INFO | quant.engine | backtest done | bars=35,137 trades=39 final_cash=10956.11 return=9.56% dd=7.86% | 2.5 ms
[15:57:36] INFO | quant.engine | backtest done | bars=35,137 trades=41 final_cash=9149.06 return=-8.51% dd=12.31% | 2.7 ms
[15:57:36] INFO | quant.engine | backtest done | bars=35,137 trades=36 final_cash=10772.40 return=7.72% dd=11.91% | 2.3 ms
[15:57:36] INFO | quant.engine | backtest done | bars=35,137 trades=39 final_cash=9387.99 return=-6.12% dd=10.79% | 2.2 ms
[15:57:36] INFO | quant.engine | backtest done | bars=35,137 trades=39 final_cash=10830.77 return=8.31% dd=7.86% | 2.6 ms
[15:57:36] INFO | quant.engine | backtest done | bars=35,137 trades=42 final_cash=9187.31 return=-8.13% dd=11.95% | 2.8 ms
[15:57:36] INFO | quant.engine | backtest done | bars=35,137 trades=35 final_cash=10435.54 return=4.36% dd=13.27% | 2.6 ms
[15:57:36] INFO | quant.engine | backtest done | bars=35,137 trades=41 final_cash=8734.32 return=-12.66% dd=16.09% | 2.5 ms

2024Q4: 73 trades  -3.2R  (43s)

[15:57:37] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:37] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:37] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:37] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:37] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:37] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:38] INFO | quant.engine | backtest done | bars=34,849 trades=31 final_cash=8524.16 return=-14.76% dd=19.54% | 3.4 ms
[15:57:38] INFO | quant.engine | backtest done | bars=34,849 trades=27 final_cash=12007.17 return=20.07% dd=5.19% | 3.2 ms
[15:57:38] INFO | quant.engine | backtest done | bars=34,849 trades=31 final_cash=8879.58 return=-11.20% dd=17.09% | 3.4 ms
[15:57:38] INFO | quant.engine | backtest done | bars=34,849 trades=27 final_cash=12419.57 return=24.20% dd=4.73% | 3.6 ms
[15:57:38] INFO | quant.engine | backtest done | bars=34,849 trades=32 final_cash=8809.24 return=-11.91% dd=15.69% | 4.6 ms
[15:57:38] INFO | quant.engine | backtest done | bars=34,849 trades=30 final_cash=11430.91 return=14.31% dd=5.19% | 3.9 ms
[15:57:39] INFO | quant.engine | backtest done | bars=34,849 trades=41 final_cash=8529.82 return=-14.70% dd=19.33% | 2.7 ms
[15:57:39] INFO | quant.engine | backtest done | bars=34,849 trades=31 final_cash=11602.73 return=16.03% dd=5.19% | 2.8 ms
[15:57:39] INFO | quant.engine | backtest done | bars=34,849 trades=41 final_cash=8753.71 return=-12.46% dd=16.22% | 3.6 ms
[15:57:39] INFO | quant.engine | backtest done | bars=34,849 trades=32 final_cash=11162.40 return=11.62% dd=5.19% | 3.8 ms
[15:57:39] INFO | quant.engine | backtest done | bars=34,849 trades=37 final_cash=7956.64 return=-20.43% dd=24.75% | 3.3 ms
[15:57:39] INFO | quant.engine | backtest done | bars=34,849 trades=28 final_cash=11870.45 return=18.70% dd=5.19% | 3.3 ms

2025Q1: 58 trades  -1.5R  (45s)

[15:57:39] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:39] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:39] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:39] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:39] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:39] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:41] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=9952.38 return=-0.48% dd=6.36% | 3.5 ms
[15:57:41] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=9760.85 return=-2.39% dd=9.00% | 2.3 ms
[15:57:41] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=10392.46 return=3.92% dd=5.46% | 3.1 ms
[15:57:41] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=10166.29 return=1.66% dd=7.22% | 2.4 ms
[15:57:41] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=9919.10 return=-0.81% dd=6.57% | 4.4 ms
[15:57:41] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=9752.69 return=-2.47% dd=9.00% | 3.1 ms
[15:57:41] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=10267.26 return=2.67% dd=4.61% | 2.8 ms
[15:57:42] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=9422.47 return=-5.78% dd=9.48% | 2.3 ms
[15:57:42] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=10267.26 return=2.67% dd=4.61% | 3.9 ms
[15:57:42] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=9422.47 return=-5.78% dd=9.48% | 3.1 ms
[15:57:42] INFO | quant.engine | backtest done | bars=35,137 trades=35 final_cash=9896.64 return=-1.03% dd=7.74% | 3.0 ms
[15:57:42] INFO | quant.engine | backtest done | bars=35,137 trades=28 final_cash=9999.79 return=-0.00% dd=6.27% | 2.4 ms

2025Q2: 56 trades  -7.1R  (48s)

[15:57:42] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:42] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:42] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:42] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:42] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:42] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:44] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=10239.84 return=2.40% dd=8.36% | 3.4 ms
[15:57:44] INFO | quant.engine | backtest done | bars=35,137 trades=34 final_cash=9484.95 return=-5.15% dd=9.74% | 2.9 ms
[15:57:44] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=10685.96 return=6.86% dd=6.40% | 3.5 ms
[15:57:44] INFO | quant.engine | backtest done | bars=35,137 trades=34 final_cash=9736.37 return=-2.64% dd=8.02% | 3.2 ms
[15:57:44] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=10233.52 return=2.34% dd=8.80% | 4.2 ms
[15:57:44] INFO | quant.engine | backtest done | bars=35,137 trades=35 final_cash=9164.39 return=-8.36% dd=11.53% | 4.0 ms
[15:57:44] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=10447.14 return=4.47% dd=6.43% | 3.4 ms
[15:57:44] INFO | quant.engine | backtest done | bars=35,137 trades=34 final_cash=9511.99 return=-4.88% dd=9.87% | 2.9 ms
[15:57:44] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=10464.58 return=4.65% dd=6.87% | 4.1 ms
[15:57:45] INFO | quant.engine | backtest done | bars=35,137 trades=35 final_cash=9164.84 return=-8.35% dd=11.28% | 4.0 ms
[15:57:45] INFO | quant.engine | backtest done | bars=35,137 trades=25 final_cash=9725.52 return=-2.74% dd=9.03% | 3.8 ms
[15:57:45] INFO | quant.engine | backtest done | bars=35,137 trades=29 final_cash=10167.78 return=1.68% dd=5.04% | 3.1 ms

2025Q3: 61 trades  -1.0R  (51s)

[15:57:45] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:45] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:45] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:45] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:45] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:45] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:46] INFO | quant.engine | backtest done | bars=35,137 trades=40 final_cash=9219.46 return=-7.81% dd=13.36% | 3.0 ms
[15:57:47] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=10248.98 return=2.49% dd=6.76% | 2.6 ms
[15:57:47] INFO | quant.engine | backtest done | bars=35,137 trades=40 final_cash=9808.54 return=-1.91% dd=9.89% | 2.9 ms
[15:57:47] INFO | quant.engine | backtest done | bars=35,137 trades=37 final_cash=10791.57 return=7.92% dd=5.94% | 2.8 ms
[15:57:47] INFO | quant.engine | backtest done | bars=35,137 trades=43 final_cash=9148.27 return=-8.52% dd=14.03% | 3.6 ms
[15:57:47] INFO | quant.engine | backtest done | bars=35,137 trades=40 final_cash=9794.56 return=-2.05% dd=6.94% | 3.1 ms
[15:57:47] INFO | quant.engine | backtest done | bars=35,137 trades=39 final_cash=8961.07 return=-10.39% dd=15.73% | 3.4 ms
[15:57:47] INFO | quant.engine | backtest done | bars=35,137 trades=38 final_cash=10021.95 return=0.22% dd=7.41% | 2.4 ms
[15:57:47] INFO | quant.engine | backtest done | bars=35,137 trades=42 final_cash=8891.88 return=-11.08% dd=16.38% | 4.0 ms
[15:57:47] INFO | quant.engine | backtest done | bars=35,137 trades=40 final_cash=9595.98 return=-4.04% dd=8.09% | 3.1 ms
[15:57:48] INFO | quant.engine | backtest done | bars=35,137 trades=41 final_cash=9188.13 return=-8.12% dd=12.88% | 3.0 ms
[15:57:48] INFO | quant.engine | backtest done | bars=35,137 trades=40 final_cash=10006.27 return=0.06% dd=9.31% | 3.0 ms

2025Q4: 77 trades  -14.0R  (54s)

[15:57:48] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:48] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:48] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:48] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:48] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:48] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:50] INFO | quant.engine | backtest done | bars=34,849 trades=33 final_cash=9322.54 return=-6.77% dd=13.46% | 4.2 ms
[15:57:50] INFO | quant.engine | backtest done | bars=34,849 trades=34 final_cash=11160.77 return=11.61% dd=5.19% | 3.1 ms
[15:57:50] INFO | quant.engine | backtest done | bars=34,849 trades=33 final_cash=9754.12 return=-2.46% dd=11.15% | 4.2 ms
[15:57:50] INFO | quant.engine | backtest done | bars=34,849 trades=34 final_cash=11666.40 return=16.66% dd=4.64% | 3.0 ms
[15:57:50] INFO | quant.engine | backtest done | bars=34,849 trades=35 final_cash=9420.17 return=-5.80% dd=13.04% | 5.3 ms
[15:57:50] INFO | quant.engine | backtest done | bars=34,849 trades=38 final_cash=10975.72 return=9.76% dd=5.38% | 4.0 ms
[15:57:50] INFO | quant.engine | backtest done | bars=34,849 trades=34 final_cash=9523.83 return=-4.76% dd=10.96% | 4.2 ms
[15:57:50] INFO | quant.engine | backtest done | bars=34,849 trades=36 final_cash=11175.73 return=11.76% dd=6.36% | 3.0 ms
[15:57:51] INFO | quant.engine | backtest done | bars=34,849 trades=35 final_cash=9575.25 return=-4.25% dd=10.96% | 5.8 ms
[15:57:51] INFO | quant.engine | backtest done | bars=34,849 trades=38 final_cash=10847.29 return=8.47% dd=6.61% | 4.1 ms
[15:57:51] INFO | quant.engine | backtest done | bars=34,849 trades=36 final_cash=9260.63 return=-7.39% dd=14.43% | 4.2 ms
[15:57:51] INFO | quant.engine | backtest done | bars=34,849 trades=37 final_cash=11317.55 return=13.18% dd=5.29% | 2.8 ms

2026Q1: 67 trades  +6.0R  (57s)

[15:57:51] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:51] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:51] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:51] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:51] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:51] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:53] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=9452.95 return=-5.47% dd=12.06% | 2.7 ms
[15:57:53] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=9432.36 return=-5.68% dd=13.28% | 3.0 ms
[15:57:53] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=10089.07 return=0.89% dd=8.11% | 2.5 ms
[15:57:53] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=9835.06 return=-1.65% dd=11.30% | 2.9 ms
[15:57:53] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=9804.92 return=-1.95% dd=9.27% | 2.9 ms
[15:57:53] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=9544.69 return=-4.55% dd=13.80% | 3.6 ms
[15:57:53] INFO | quant.engine | backtest done | bars=35,137 trades=32 final_cash=9916.93 return=-0.83% dd=10.37% | 2.4 ms
[15:57:54] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=9946.99 return=-0.53% dd=13.43% | 3.1 ms
[15:57:54] INFO | quant.engine | backtest done | bars=35,137 trades=34 final_cash=9972.45 return=-0.28% dd=8.86% | 2.8 ms
[15:57:54] INFO | quant.engine | backtest done | bars=35,137 trades=30 final_cash=9835.26 return=-1.65% dd=13.43% | 3.3 ms
[15:57:54] INFO | quant.engine | backtest done | bars=35,137 trades=33 final_cash=9258.87 return=-7.41% dd=16.01% | 3.0 ms
[15:57:54] INFO | quant.engine | backtest done | bars=35,137 trades=27 final_cash=10319.20 return=3.19% dd=12.28% | 3.5 ms

2026Q2: 57 trades  -15.7R  (60s)

[15:57:54] INFO | quant.data | cache HIT  binance BTCUSDT 5m -> pushdown load
[15:57:54] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:54] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:54] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:54] INFO | quant.data | cache HIT  binance BTCUSDT 15m -> pushdown load
[15:57:54] INFO | quant.data | cache HIT  binance BTCUSDT 1h -> pushdown load
[15:57:55] INFO | quant.engine | backtest done | bars=26,209 trades=25 final_cash=10239.55 return=2.40% dd=8.12% | 2.0 ms
[15:57:55] INFO | quant.engine | backtest done | bars=26,209 trades=15 final_cash=9428.78 return=-5.71% dd=8.08% | 2.4 ms
[15:57:56] INFO | quant.engine | backtest done | bars=26,209 trades=25 final_cash=10869.21 return=8.69% dd=5.96% | 1.9 ms
[15:57:56] INFO | quant.engine | backtest done | bars=26,209 trades=15 final_cash=10190.41 return=1.90% dd=5.37% | 2.3 ms
[15:57:56] INFO | quant.engine | backtest done | bars=26,209 trades=25 final_cash=10472.55 return=4.73% dd=6.49% | 2.7 ms
[15:57:56] INFO | quant.engine | backtest done | bars=26,209 trades=21 final_cash=9592.18 return=-4.08% dd=7.02% | 2.2 ms
[15:57:56] INFO | quant.engine | backtest done | bars=26,209 trades=29 final_cash=9978.19 return=-0.22% dd=8.34% | 1.9 ms
[15:57:56] INFO | quant.engine | backtest done | bars=26,209 trades=16 final_cash=9606.80 return=-3.93% dd=8.07% | 2.4 ms
[15:57:56] INFO | quant.engine | backtest done | bars=26,209 trades=29 final_cash=10057.44 return=0.57% dd=6.72% | 2.5 ms
[15:57:56] INFO | quant.engine | backtest done | bars=26,209 trades=23 final_cash=9718.81 return=-2.81% dd=6.95% | 2.2 ms
[15:57:56] INFO | quant.engine | backtest done | bars=26,209 trades=28 final_cash=10297.52 return=2.98% dd=10.24% | 2.1 ms
[15:57:56] INFO | quant.engine | backtest done | bars=26,209 trades=17 final_cash=9224.47 return=-7.76% dd=10.07% | 2.5 ms

2026Q3: 40 trades  -7.2R  (62s)

## 2 · The strategy itself

`R / trade` after costs is the number that matters. The zero-cost row says whether a loss is the
rule or the costs: a strategy positive at zero cost and negative after it has an entry that is
not worth what it costs to take — a different problem from an entry with nothing in it.

In [3]:
ev.baseline()

,run,trades,R / trade,win %,train R,forward R,quarters > 0
0,as set,1194,-0.157,26.8,-149.3,-38.3,2/19
1,"as set, zero cost",1199,0.080,27.3,2.6,93.3,15/19

In [4]:
ev.by_quarter()

quarter,2022Q1,2022Q2,2022Q3,2022Q4,2023Q1,2023Q2,2023Q3,2023Q4,2024Q1,2024Q2,2024Q3,2024Q4,2025Q1,2025Q2,2025Q3,2025Q4,2026Q1,2026Q2,2026Q3
run,,,,,,,,,,,,,,,,,,,
as set,-9.4,-20.1,-24.2,-4.1,-2.1,-15.8,-38.8,-18.0,-13.2,-3.5,5.4,-3.2,-1.5,-7.1,-1.0,-14.0,6.0,-15.7,-7.2
"as set, zero cost",8.0,-8.0,-15.5,5.1,8.0,0.7,-8.3,0.7,-1.1,13.0,14.5,10.7,8.5,6.9,13.2,3.0,18.7,0.9,16.9
both,-9.7,-23.2,-22.1,-7.6,4.3,-16.4,-41.6,-16.8,-13.4,-10.2,-10.0,-1.9,-5.3,-7.0,-4.9,-26.3,3.1,-2.7,-2.9
fvg exit,-6.3,-23.6,-21.7,-9.6,7.4,-17.8,-42.3,-17.4,-15.4,-6.8,-7.2,0.1,-4.5,-7.0,2.4,-20.1,5.1,-3.9,-5.2
move target,-6.2,-20.6,-21.6,-4.4,-0.6,-11.6,-39.2,-17.4,-14.4,-4.8,-0.6,-2.1,-1.9,-6.5,-7.1,-19.2,2.5,-8.3,0.1
no confirmation,-4.5,-2.4,-27.6,-3.7,5.2,-4.7,-40.8,-9.2,-8.9,-7.4,1.2,-13.3,-9.3,-3.6,3.9,-18.7,5.5,-5.7,-9.0

## 3 · Its questions

Each arm against the strategy as set, per quarter. Read in this order:

1. **the verdict line** — if the train ranking does not survive forward, or no `|t|` reaches
   ~2.5, the table is noise however large a number in it looks;
2. **forward dR and forward beat** — the arm's effect on quarters the choice never saw;
3. **fwd trim3** — the same with each run's three best trades removed; a big gap from forward dR
   means one or two outsized trades are doing the work.

In [5]:
print(ev.verdict())
ev.arms()

4 arms over 19 quarters.
train -> forward rank correlation: +0.20  (the train ranking did not survive)
largest |t|: 1.12  -- below 2.5, nothing here beats noise
identical to the strategy as set, so not run: ['neither']

,arm,train dR,train beat,forward dR,forward beat,fwd trim3,t,trades
0,no confirmation,45.3,7/10,-10.4,3/9,-10.4,1.12,48
1,move target,8.4,5/10,-4.9,4/9,-4.9,0.21,61
2,fvg exit,-4.3,4/10,-2.1,5/9,-2.1,-0.27,48
3,both,-7.4,3/10,-19.6,4/9,-19.5,-0.99,91

---
### What to change

| want | where |
|---|---|
| evaluate another strategy | `STRATEGY` in `evaluate_config.py` |
| other quarters | `TRAIN` / `FORWARD` in `evaluate_config.py` |
| other arms | `COMPARE` in `strategies/<name>.py` — the lab shows the same arms |